### ISSUE TITLE
Criação da página sobre

### ISSUE THREAD

**Issue by ValeriaMiranda** [LuizMarcello/github-master#4]
Vocês poderiam criar uma página de sobre? Agradeço.

**Comment by LuizMarcello** [comment]
A página já está em produção.

**Comment by ValeriaMiranda** [comment]
Obrigado, estou aguardando.

________________________________
De: Luiz Marcello <notifications@github.com>
Enviado: terça-feira, 12 de fevereiro de 2019 20:14
Para: LuizMarcello/github-master
Cc: ValeriaMiranda; Author
Assunto: Re: [LuizMarcello/github-master] Criação da página sobre (#4)


A página já está em produção.
